<?php
$defaults=array(
   'title' => __('Categories', 'moo-collapsing-cat'),
   'showPostCount' => true,
   'inExclude' => 'exclude',
   'inExcludeCats' => '',
   'showPosts' => true, 
   'showPages' => false,
   'linkToCat' => true,
   'olderThan' => 0,
   'excludeAll' => '0',
   'catSortOrder' => 'ASC',
   'catSort' => 'catName',
   'postSortOrder' => 'ASC',
   'postSort' => 'postTitle',
   'expand' => '0',
   'defaultExpand' => '',
   'debug'=>'0',
   'postTitleLength' => 0,
   'animate' => 0,
   'catfeed' => 'none',
   'catTag' => 'cat',
   'postDateAppend' => 'after',
   'postDateFormat' => 'm/d',
   'showPostDate' => false,
   'useCookies' => true,
   'postsBeforeCats' => false,
   'expandCatPost' => true,
   'showTopLevel' => true
);
?>